# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "demo2-stoyandg-bucket-for-storing"
    dynamodb_table = "demo2_terraform_state_dynamodb"
    encrypt        = false
    key            = "./terraform.tfstate"
    region         = "eu-central-1"
  }
}

## Terraform backend ##
