version: 0.2

env:
  variables:
    CI: "true"
    REPOSITORY_REGION: "eu-central-1"
    TERRAFORM_V: "1.3.5"
    TERRAGRUNT_V: "0.42.5"

phases:
  pre_build:
    commands:
      - cd "${CODEBUILD_SRC_DIR}/modules/codebuild/"
      - chmod +x pre-build.sh build-and-push.sh deploy.sh status.sh
      - ./pre-build.sh

  build:
    commands:
      - ./build-and-push.sh
  
  post_build:
    commands:
      - cd "${CODEBUILD_SRC_DIR}/modules/codebuild/"
      - ./deploy.sh
      - cd "${CODEBUILD_SRC_DIR}/modules/codebuild/"
      - ./status.sh
